services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./backend:/app
      - ./backend/database-development.sqlite:/app/database-development.sqlite
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - VITE_TARGET_URL=http://backend:9090
    depends_on:
      - backend
