services:
  - type: web
    name: museum-curator
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
