# Exported from Render on 2025-03-11T13:05:02Z
services:
  - type: web
    name: museum-curator-api
    runtime: node
    repo: https://github.com/Rizq0/museum-curator
    plan: free
    envVars:
      - key: NODE_ENV
        sync: false
    region: frankfurt
    buildCommand: yarn install
    startCommand: yarn start
    rootDir: backend
version: "1"
